language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda config --add channels hjkgroup
  - conda build --python $TRAVIS_PYTHON_VERSION conda-recipe
  - conda install pytest
  - conda install numpy
  - conda install pip
  - pip install pyclustering 
  - conda install pytest

script:
  # Your test script goes here
  - pip install -e ./
  - pytest test/
  

