language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - pip install pytest
  - pip install numpy
  - pip install pyclustering 

script:
  # Your test script goes here
  - pip install -e ./
  - pytest test/
  

